// ToursPackages.js — central data source

export const tours = [
  {
    id: 1,
    slug: 'leh-ladakh-bike-tour-turtuk-6n7d',
    title: 'LEH LADAKH BIKE TOUR WITH TURTUK VILLAGE ',
    price: '₹24,499',
    priceNote: 'per person',
    image: '/Image/LEHLADAKHBIKETOUR.png',
    stats: [
      { icon: '/Image/World.png',    label: 'Altitude', value: '18,380 ft' },
      { icon: '/Image/Location.png', label: 'Distance', value: '480 km' },
      { icon: '/Image/Calender.png', label: 'Duration', value: '6N / 7D' },
      { icon: '/Image/Bed.png',      label: 'Stay',     value: 'Hotel / Camp' },
      { icon: '/Image/Food.png',     label: 'Meals',    value: 'Breakfast & Dinner' },
    ],
    overview: "Explore the crown jewel of Ladakh on two wheels. This 7-day adventure takes you from the high-altitude desert of Leh all the way to Turtuk — the last village before the Pakistan border — crossing some of the world's highest motorable passes and riding through surreal lunar landscapes.",
    highlights: [
      'Ride through Khardung La (18,380 ft) — one of the highest motorable roads',
      'Visit Turtuk village — India\'s northernmost accessible point near the LoC',
      'Explore Nubra Valley\'s sand dunes and Bactrian camels',
      'Overnight stay at Pangong Lake with breathtaking sunrise views',
      'Expert ride leader, backup vehicle & mechanic throughout',
      'Small batch of max 10 riders for a personal experience',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Leh', desc: 'Arrival, acclimatization, and bike allocation. Evening orientation briefing.' },
      { day: 'Day 2', title: 'Leh – Nubra Valley via Khardung La', desc: 'Cross the mighty Khardung La at 18,380 ft. Descend into Nubra Valley. Camel safari at Hunder Sand Dunes.' },
      { day: 'Day 3', title: 'Nubra – Turtuk Village', desc: 'Ride to Turtuk — India\'s northernmost village. Explore its unique Balti culture and scenic beauty.' },
      { day: 'Day 4', title: 'Turtuk – Shyok – Pangong', desc: 'Ride along the Shyok River to the world-famous Pangong Lake. Overnight at lakeside camp.' },
      { day: 'Day 5', title: 'Pangong – Leh via Chang La', desc: 'Witness a magical sunrise on the lake, then return via Chang La (17,586 ft). Evening in Leh.' },
      { day: 'Day 6', title: 'Leh Sightseeing', desc: 'Visit Leh Palace, Shanti Stupa, Thiksey and Hemis monasteries.' },
      { day: 'Day 7', title: 'Depart Leh', desc: 'Transfer to airport/bus station. Tour ends with lifelong memories.' },
    ],
    inclusions: ['Bike with fuel', 'Accommodation (hotel/camp)', 'Breakfast & Dinner daily', 'All permit fees', 'Oxygen cylinder & first aid', 'Expert ride leader & backup vehicle'],
    exclusions: ['Flights / train to Leh', 'Lunch', 'Personal expenses', 'Travel insurance'],
    whatsapp: '919541438044',
  },
  {
    id: 2,
    slug: 'srinagar-to-manali-hanle-umling-la-11n12d',
    title: 'SRINAGAR TO MANALI WITH HANLE AND UMLING LA ',
    price: '₹41,999',
    priceNote: 'per person',
    image: '/Image/SRINAGARTOMANALI.png',
    stats: [
      { icon: '/Image/World.png',    label: 'Altitude', value: '19,024 ft' },
      { icon: '/Image/Location.png', label: 'Distance', value: '1,200 km' },
      { icon: '/Image/Calender.png', label: 'Duration', value: '11N / 12D' },
      { icon: '/Image/Bed.png',      label: 'Stay',     value: 'Hotel / Camp' },
      { icon: '/Image/Food.png',     label: 'Meals',    value: 'Breakfast & Dinner' },
    ],
    overview: "The ultimate Himalayan crossing — Srinagar to Manali with detours to Hanle Observatory and the record-breaking Umling La. This 12-day epic covers the breathtaking Kashmir Valley, the Zanskar ranges, the remote dark-sky site of Hanle, and the world's highest motorable road at Umling La (19,024 ft).",
    highlights: [
      'Ride Umling La (19,024 ft) — the world\'s highest motorable road',
      'Star-gazing at Hanle Dark Sky Reserve',
      'Dal Lake shikara ride in Srinagar',
      'Cross Zoji La, Fotu La, Baralacha La, and Rohtang Pass',
      'Pangong Lake, Nubra Valley, and Tso Moriri all in one tour',
      'Full mechanical support and experienced lead riders',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Srinagar', desc: 'Welcome to Srinagar. Shikara ride on Dal Lake. Overnight in houseboat or hotel.' },
      { day: 'Day 2', title: 'Srinagar – Kargil via Zoji La', desc: 'Cross Zoji La and Fotu La passes. Ride through Drass (2nd coldest inhabited place). Arrive Kargil.' },
      { day: 'Day 3', title: 'Kargil – Leh via Lamayuru', desc: 'Ride through the moon landscape of Lamayuru Monastery. Arrive Leh.' },
      { day: 'Day 4', title: 'Leh Acclimatization', desc: 'Rest day. Visit Leh Palace, Shanti Stupa, and local markets.' },
      { day: 'Day 5', title: 'Leh – Nubra via Khardung La', desc: 'Conquer Khardung La (18,380 ft). Hunder dunes and camel safari.' },
      { day: 'Day 6', title: 'Nubra – Pangong Lake', desc: 'Ride via Shyok River to the iconic blue Pangong Lake. Lakeside overnight.' },
      { day: 'Day 7', title: 'Pangong – Hanle', desc: 'Ride to Hanle (14,764 ft). Visit Hanle Observatory — one of the world\'s highest astronomical sites.' },
      { day: 'Day 8', title: 'Hanle – Umling La – Leh', desc: 'Summit Umling La at 19,024 ft — the world\'s highest motorable road. Certificate at the top!' },
      { day: 'Day 9', title: 'Leh – Sarchu via Leh–Manali Highway', desc: 'Start the Manali highway. Cross Pang and More Plains. Camp at Sarchu.' },
      { day: 'Day 10', title: 'Sarchu – Keylong via Baralacha La', desc: 'Cross Baralacha La (16,043 ft). Arrive Keylong.' },
      { day: 'Day 11', title: 'Keylong – Manali via Rohtang', desc: 'Final leg. Cross Rohtang Pass. Arrive Manali — celebration dinner!' },
      { day: 'Day 12', title: 'Depart Manali', desc: 'Tour concludes. Transfer to bus stand or airport.' },
    ],
    inclusions: ['Bike with fuel', 'Accommodation (hotel/camp)', 'Breakfast & Dinner daily', 'All permit fees', 'Oxygen cylinder & first aid', 'Summit certificate (Umling La)', 'Expert ride leader & backup vehicle'],
    exclusions: ['Flights / train', 'Lunch', 'Personal expenses', 'Travel insurance'],
    whatsapp: '919541438044',
  },
  {
    id: 3,
    slug: 'leh-ladakh-bike-trip-umling-la-7n8d',
    title: 'LEH LADAKH BIKE TRIP WITH UMLING LA',
    price: '₹28,999',
    priceNote: 'per person',
    image: 'Image/LEHLADAKHBIKETRIP.png',
    stats: [
      { icon: '/Image/World.png',    label: 'Altitude', value: '19,024 ft' },
      { icon: '/Image/Location.png', label: 'Distance', value: '650 km' },
      { icon: '/Image/Calender.png', label: 'Duration', value: '7N / 8D' },
      { icon: '/Image/Bed.png',      label: 'Stay',     value: 'Hotel / Camp' },
      { icon: '/Image/Food.png',     label: 'Meals',    value: 'Breakfast & Dinner' },
    ],
    overview: "A compact yet epic Leh-based circuit that takes you to the world's highest motorable road — Umling La at 19,024 ft. Combining Pangong Lake, Nubra Valley, Khardung La, and the remote Umling La summit, this 8-day tour is a bucket-list biker's dream.",
    highlights: [
      'Summit Umling La at 19,024 ft — world\'s highest motorable road',
      'Receive your Umling La summit certificate',
      'Ride Khardung La (18,380 ft) and Chang La (17,586 ft)',
      'Overnight camp at Pangong Lake',
      'Nubra Valley and Bactrian camel safari',
      'Expert-led small group with full support vehicle',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Leh', desc: 'Arrival and acclimatization. Rest, hydrate, and attend evening briefing.' },
      { day: 'Day 2', title: 'Leh – Nubra via Khardung La', desc: 'Cross Khardung La and descend into Nubra. Camel safari at Hunder dunes.' },
      { day: 'Day 3', title: 'Nubra – Pangong via Shyok', desc: 'Ride along the Shyok River to Pangong Tso. Lakeside camp overnight.' },
      { day: 'Day 4', title: 'Pangong – Leh via Chang La', desc: 'Sunrise at the lake, then return via Chang La. Evening in Leh.' },
      { day: 'Day 5', title: 'Leh – Hanle', desc: 'Ride to the remote Hanle Plateau. Visit Hanle Observatory.' },
      { day: 'Day 6', title: 'Hanle – Umling La – Leh', desc: 'Epic day — summit Umling La at 19,024 ft. Collect your certificate. Return to Leh.' },
      { day: 'Day 7', title: 'Leh Local Sightseeing', desc: 'Explore Leh Palace, Thiksey Monastery, and Hall of Fame.' },
      { day: 'Day 8', title: 'Depart Leh', desc: 'Transfer to airport. Tour concludes.' },
    ],
    inclusions: ['Bike with fuel', 'Hotel/camp accommodation', 'Breakfast & Dinner daily', 'All permit fees', 'Oxygen cylinder & first aid', 'Summit certificate', 'Expert ride leader & backup vehicle'],
    exclusions: ['Flights / train to Leh', 'Lunch', 'Personal expenses', 'Travel insurance'],
    whatsapp: '919541438044',
  },
  {
    id: 4,
    slug: 'manali-to-srinagar-hanle-umling-la-11n12d',
    title: 'MANALI TO SRINAGAR WITH HANLE & UMLING LA ',
    price: '₹41,999',
    priceNote: 'per person',
    image: 'Image/MANALITOSRINAGAR.png',
    stats: [
      { icon: '/Image/World.png',    label: 'Altitude', value: '19,024 ft' },
      { icon: '/Image/Location.png', label: 'Distance', value: '1,200 km' },
      { icon: '/Image/Calender.png', label: 'Duration', value: '11N / 12D' },
      { icon: '/Image/Bed.png',      label: 'Stay',     value: 'Hotel / Camp' },
      { icon: '/Image/Food.png',     label: 'Meals',    value: 'Breakfast & Dinner' },
    ],
    overview: "Begin your epic Himalayan odyssey in Manali and conclude in Srinagar, conquering the mighty Umling La (19,024 ft), Hanle's dark sky sanctuary, and the entire Leh–Ladakh circuit. 12 days of pure riding bliss across the highest roads on Earth.",
    highlights: [
      'Umling La summit at 19,024 ft — world record highest motorable road',
      'Star-gazing at Hanle Dark Sky Reserve',
      'Ride Baralacha La, More Plains, Tanglang La',
      'Pangong Lake and Nubra Valley exploration',
      'Dal Lake, Mughal Gardens, and Srinagar sightseeing',
      'Full backup support, mechanic, and oxygen on board',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Manali', desc: 'Arrival and acclimatization. Bike handover and route briefing.' },
      { day: 'Day 2', title: 'Manali – Jispa via Rohtang', desc: 'Cross Rohtang Pass (13,050 ft). Camp at Jispa by the Bhaga River.' },
      { day: 'Day 3', title: 'Jispa – Sarchu via Baralacha La', desc: 'Cross Baralacha La (16,043 ft). Arrive Sarchu campsite.' },
      { day: 'Day 4', title: 'Sarchu – Leh via Tanglang La', desc: 'Cross Tanglang La (17,480 ft) and the More Plains. Arrive Leh.' },
      { day: 'Day 5', title: 'Leh Acclimatization & Sightseeing', desc: 'Explore Leh Palace, Thiksey Monastery, Hall of Fame.' },
      { day: 'Day 6', title: 'Leh – Nubra via Khardung La', desc: 'Ride Khardung La (18,380 ft). Nubra Valley & camel safari.' },
      { day: 'Day 7', title: 'Nubra – Pangong via Shyok', desc: 'Scenic Shyok River ride to Pangong Tso. Lakeside overnight.' },
      { day: 'Day 8', title: 'Pangong – Hanle', desc: 'Cross the Chushul plateau to Hanle. Night sky photography.' },
      { day: 'Day 9', title: 'Hanle – Umling La – Leh', desc: 'Summit the world\'s highest motorable road at 19,024 ft. Certificate at the top!' },
      { day: 'Day 10', title: 'Leh – Kargil', desc: 'Ride via Lamayuru and Fotu La. Arrive Kargil.' },
      { day: 'Day 11', title: 'Kargil – Srinagar via Zoji La', desc: 'Cross Zoji La and Sonamarg. Arrive Srinagar. Shikara ride on Dal Lake.' },
      { day: 'Day 12', title: 'Depart Srinagar', desc: 'Tour concludes. Transfer to airport.' },
    ],
    inclusions: ['Bike with fuel', 'Accommodation (hotel/camp)', 'Breakfast & Dinner daily', 'All permit fees', 'Oxygen cylinder & first aid', 'Summit certificate', 'Expert ride leader & backup vehicle'],
    exclusions: ['Flights / train', 'Lunch', 'Personal expenses', 'Travel insurance'],
    whatsapp: '919541438044',
  },
  {
    id: 5,
    slug: 'manali-leh-manali-umling-la-demchok',
    title: 'MANALI–LEH–MANALI (WITH UMLING-LA & DEMCHOK)',
    price: '₹38,999',
    priceNote: 'per person',
    image: '/Image/MANALILEHMANALI.png',
    stats: [
      { icon: '/Image/World.png',    label: 'Altitude', value: '19,024 ft' },
      { icon: '/Image/Location.png', label: 'Distance', value: '1,000 km' },
      { icon: '/Image/Calender.png', label: 'Duration', value: '11N / 12D' },
      { icon: '/Image/Bed.png',      label: 'Stay',     value: 'Hotel / Camp' },
      { icon: '/Image/Food.png',     label: 'Meals',    value: 'Breakfast & Dinner' },
    ],
    overview: "A circular Manali–Leh–Manali tour with game-changing detours to the world's highest motorable road at Umling La and the southernmost tip of Ladakh at Demchok village near the Indo-China border. Return with stories no one else can tell.",
    highlights: [
      'Round-trip from Delhi Bus Stand to Manali and back',
      'Summit Umling La (19,024 ft) — the world\'s highest road',
      'Visit Demchok — Ladakh\'s southernmost accessible village',
      'Pangong Lake, Nubra Valley, Tso Moriri',
      'Baralacha La, Tanglang La, and Rohtang crossings',
      'Full mechanical and medical support throughout',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Delhi – Manali (Overnight Bus)', desc: 'Depart Delhi by overnight bus to Manali.' },
      { day: 'Day 2', title: 'Arrive Manali & Acclimatize', desc: 'Arrive Manali. Rest and acclimatization. Bike briefing.' },
      { day: 'Day 3', title: 'Manali – Jispa via Rohtang La', desc: 'Cross Rohtang (13,050 ft) and Baralacha La (16,043 ft). Camp at Jispa.' },
      { day: 'Day 4', title: 'Jispa – Leh via Sarchu & Tanglang La', desc: 'Cross Tanglang La (17,480 ft) and the More Plains. Arrive Leh.' },
      { day: 'Day 5', title: 'Leh Sightseeing & Rest', desc: 'Leh Palace, Thiksey, Shanti Stupa, and Hall of Fame.' },
      { day: 'Day 6', title: 'Leh – Nubra via Khardung La', desc: 'Cross Khardung La (18,380 ft). Explore Nubra Valley.' },
      { day: 'Day 7', title: 'Nubra – Pangong via Shyok', desc: 'Ride to Pangong Tso via Shyok River. Lakeside camp.' },
      { day: 'Day 8', title: 'Pangong – Demchok – Tso Moriri', desc: 'Ride to Demchok — the southernmost village. Overnight at Tso Moriri.' },
      { day: 'Day 9', title: 'Umling La Summit Day', desc: 'Conquer Umling La at 19,024 ft. Collect your world-record certificate. Return to Leh.' },
      { day: 'Day 10', title: 'Leh – Sarchu', desc: 'Begin return journey. Camp at Sarchu on the highway.' },
      { day: 'Day 11', title: 'Sarchu – Manali via Baralacha La', desc: 'Cross Baralacha La and descend to Manali.' },
      { day: 'Day 12', title: 'Manali – Delhi (Overnight Bus)', desc: 'Overnight bus to Delhi. Tour concludes.' },
    ],
    inclusions: ['Bike with fuel', 'Accommodation (hotel/camp)', 'Breakfast & Dinner daily', 'Delhi–Manali–Delhi bus', 'All permit fees', 'Summit certificate', 'Expert ride leader & backup vehicle'],
    exclusions: ['Lunch', 'Personal expenses', 'Travel insurance', 'Flights'],
    whatsapp: '919541438044',
  },
  {
    id: 6,
    slug: 'leh-to-leh-zanskar-adventure-7n8d',
    title: 'LEH TO LEH: THE ZANSKAR ADVENTURE ',
    price: '₹29,999',
    priceNote: 'per person',
    image: '/Image/lehlake.png',
    stats: [
      { icon: '/Image/World.png',    label: 'Altitude', value: '14,764 ft' },
      { icon: '/Image/Location.png', label: 'Distance', value: '900 km' },
      { icon: '/Image/Calender.png', label: 'Duration', value: '7N / 8D' },
      { icon: '/Image/Bed.png',      label: 'Stay',     value: 'Hotel / Camp' },
      { icon: '/Image/Food.png',     label: 'Meals',    value: 'Breakfast & Dinner' },
    ],
    overview: "A circular Leh-to-Leh route that ventures deep into the remote Zanskar Valley — one of Ladakh's most dramatic and least-visited regions. Ride along gorges, frozen river trails, and ancient monastery routes before looping back to Leh through the Manali Highway.",
    highlights: [
      'Ride the incredible Zanskar gorge roads',
      'Visit Rangdum and Padum — capitals of Zanskar',
      'Explore Phugtal Monastery via a short trek',
      'Cross Penzi La (14,436 ft) and Sinthan Top',
      'Scenic Drang-Drung Glacier viewpoint',
      'Circular route — start and end in Leh',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Leh', desc: 'Arrival. Acclimatization and bike briefing.' },
      { day: 'Day 2', title: 'Leh – Kargil via Lamayuru', desc: 'Ride past Moonland Lamayuru and Fotu La. Arrive Kargil.' },
      { day: 'Day 3', title: 'Kargil – Rangdum via Penzi La', desc: 'Cross Penzi La (14,436 ft). Camp at Rangdum.' },
      { day: 'Day 4', title: 'Rangdum – Padum', desc: 'Reach Padum, the capital of Zanskar. Visit Stongdey Monastery.' },
      { day: 'Day 5', title: 'Padum – Phugtal & Back', desc: 'Day excursion to Phugtal Gompa — a stunning cave monastery. Return to Padum.' },
      { day: 'Day 6', title: 'Padum – Sarchu via Shinku La', desc: 'Cross Shinku La (16,010 ft). Camp at Sarchu.' },
      { day: 'Day 7', title: 'Sarchu – Leh via Leh-Manali Highway', desc: 'Ride back to Leh via Tanglang La (17,480 ft) and the More Plains.' },
      { day: 'Day 8', title: 'Depart Leh', desc: 'Transfer to airport. Tour ends.' },
    ],
    inclusions: ['Bike with fuel', 'Hotel/camp accommodation', 'Breakfast & Dinner daily', 'All permit fees', 'Oxygen cylinder & first aid', 'Expert ride leader & backup vehicle'],
    exclusions: ['Flights / train to Leh', 'Lunch', 'Personal expenses', 'Travel insurance'],
    whatsapp: '919541438044',
  },
  {
    id: 7,
    slug: 'manali-to-srinagar-umlingla-demchok-11n12d',
    title: 'MANALI TO SRINAGAR WITH [UMLINGLA & DEMCHOK]',
    price: '₹41,999',
    priceNote: 'per person',
    image: '/Image/UMLINGLADEMCHOK.png',
    stats: [
      { icon: '/Image/World.png',    label: 'Altitude', value: '19,024 ft' },
      { icon: '/Image/Location.png', label: 'Distance', value: '1,300 km' },
      { icon: '/Image/Calender.png', label: 'Duration', value: '11N / 12D' },
      { icon: '/Image/Bed.png',      label: 'Stay',     value: 'Hotel / Camp' },
      { icon: '/Image/Food.png',     label: 'Meals',    value: 'Breakfast & Dinner' },
    ],
    overview: "The most comprehensive Himalayan motorcycle tour — Manali to Srinagar with Umling La (world's highest road) and Demchok (Ladakh's southernmost village on the Indo-China border). 12 days, 1,300 km, and a lifetime of stories.",
    highlights: [
      'Summit Umling La — world\'s highest motorable road at 19,024 ft',
      'Reach Demchok on the Indo-Tibet border',
      'Full Manali–Leh–Srinagar crossing',
      'Pangong Lake, Nubra Valley, Tso Moriri',
      'Dal Lake and Mughal Gardens in Srinagar',
      'Comprehensive support: mechanic, backup vehicle, oxygen',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Manali', desc: 'Acclimatization and bike allocation. Evening briefing.' },
      { day: 'Day 2', title: 'Manali – Jispa', desc: 'Cross Rohtang Pass. Overnight at Jispa.' },
      { day: 'Day 3', title: 'Jispa – Sarchu via Baralacha La', desc: 'Cross Baralacha La (16,043 ft). Camp Sarchu.' },
      { day: 'Day 4', title: 'Sarchu – Leh', desc: 'Cross Tanglang La (17,480 ft) and arrive in Leh.' },
      { day: 'Day 5', title: 'Leh Acclimatization', desc: 'Sightseeing: Leh Palace, Thiksey, Shanti Stupa.' },
      { day: 'Day 6', title: 'Leh – Nubra via Khardung La', desc: 'Khardung La (18,380 ft). Nubra dunes and camel safari.' },
      { day: 'Day 7', title: 'Nubra – Pangong via Shyok', desc: 'Shyok River road to Pangong Tso. Lakeside camp.' },
      { day: 'Day 8', title: 'Pangong – Demchok – Tso Moriri', desc: 'Ride to Demchok on the Tibet border. Overnight at Tso Moriri.' },
      { day: 'Day 9', title: 'Umling La Summit – Leh', desc: '19,024 ft. World\'s highest motorable road. Certificate awarded.' },
      { day: 'Day 10', title: 'Leh – Kargil', desc: 'Lamayuru Moonland road to Kargil.' },
      { day: 'Day 11', title: 'Kargil – Srinagar via Zoji La', desc: 'Final pass — Zoji La. Arrive Srinagar. Shikara ride.' },
      { day: 'Day 12', title: 'Depart Srinagar', desc: 'Tour concludes.' },
    ],
    inclusions: ['Bike with fuel', 'Accommodation (hotel/camp)', 'Breakfast & Dinner daily', 'All permit fees', 'Oxygen cylinder & first aid', 'Summit certificate (Umling La)', 'Expert ride leader & backup vehicle'],
    exclusions: ['Flights / train', 'Lunch', 'Personal expenses', 'Travel insurance'],
    whatsapp: '919541438044',
  },
  {
    id: 8,
    slug: 'leh-to-srinagar-bike-trip-9n10d',
    title: 'LEH TO SRINAGAR BIKE TRIP ',
    price: '₹32,999',
    priceNote: 'per person',
    image: '/Image/SRINAGARBIKETRIP.png',
    stats: [
      { icon: '/Image/World.png',    label: 'Altitude', value: '18,380 ft' },
      { icon: '/Image/Location.png', label: 'Distance', value: '850 km' },
      { icon: '/Image/Calender.png', label: 'Duration', value: '9N / 10D' },
      { icon: '/Image/Bed.png',      label: 'Stay',     value: 'Hotel / Camp' },
      { icon: '/Image/Food.png',     label: 'Meals',    value: 'Breakfast & Dinner' },
    ],
    overview: "Start in Leh, and over 10 days cross every major pass, lake, and landmark before arriving in the valley paradise of Srinagar. The classic Leh-to-Srinagar route covering Khardung La, Pangong, Nubra, Zoji La, and ending with Dal Lake.",
    highlights: [
      'Cross Khardung La (18,380 ft) and Chang La (17,586 ft)',
      'Overnight at Pangong Tso — Asia\'s largest high-altitude lake',
      'Nubra Valley with sand dunes and Bactrian camels',
      'Cross Zoji La — the gateway between Ladakh and Kashmir',
      'Shikara ride on Dal Lake in Srinagar',
      'Drass — 2nd coldest inhabited place on Earth',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Leh', desc: 'Acclimatization and bike briefing.' },
      { day: 'Day 2', title: 'Leh – Nubra via Khardung La', desc: 'Cross Khardung La (18,380 ft). Explore Nubra. Camel safari.' },
      { day: 'Day 3', title: 'Nubra – Pangong via Shyok', desc: 'Ride to Pangong Tso. Lakeside overnight.' },
      { day: 'Day 4', title: 'Pangong – Leh via Chang La', desc: 'Sunrise at the lake. Return via Chang La.' },
      { day: 'Day 5', title: 'Leh Sightseeing', desc: 'Thiksey Monastery, Hall of Fame, Shanti Stupa.' },
      { day: 'Day 6', title: 'Leh – Kargil via Lamayuru', desc: 'Moonland road. Arrive Kargil.' },
      { day: 'Day 7', title: 'Kargil – Sonamarg via Drass', desc: 'Cross Zoji La. Arrive Sonamarg — meadows of gold.' },
      { day: 'Day 8', title: 'Sonamarg – Srinagar', desc: 'Ride down the green Kashmir Valley. Arrive Srinagar.' },
      { day: 'Day 9', title: 'Srinagar Sightseeing', desc: 'Dal Lake shikara, Mughal Gardens, Shankaracharya Temple.' },
      { day: 'Day 10', title: 'Depart Srinagar', desc: 'Tour concludes. Transfer to airport.' },
    ],
    inclusions: ['Bike with fuel', 'Hotel/camp accommodation', 'Breakfast & Dinner daily', 'All permit fees', 'Oxygen cylinder & first aid', 'Expert ride leader & backup vehicle'],
    exclusions: ['Flights / train to Leh', 'Lunch', 'Personal expenses', 'Travel insurance'],
    whatsapp: '919541438044',
  },
  {
    id: 9,
    slug: 'srinagar-to-leh-bike-trip-8n9d',
    title: 'SRINAGAR TO LEH BIKE TRIP',
    price: '₹30,499',
    priceNote: 'per person',
    image: '/Image/srinagar-leh.png',
    stats: [
      { icon: '/Image/World.png',    label: 'Altitude', value: '18,380 ft' },
      { icon: '/Image/Location.png', label: 'Distance', value: '800 km' },
      { icon: '/Image/Calender.png', label: 'Duration', value: '8N / 9D' },
      { icon: '/Image/Bed.png',      label: 'Stay',     value: 'Hotel / Camp' },
      { icon: '/Image/Food.png',     label: 'Meals',    value: 'Breakfast & Dinner' },
    ],
    overview: "Begin your Himalayan journey in the garden city of Srinagar and ride through the entire Leh–Ladakh circuit, culminating in Leh. A 9-day itinerary covering Dal Lake, Zoji La, Kargil War Memorial, Lamayuru, Pangong Lake, and Nubra Valley.",
    highlights: [
      'Start with a shikara ride on Dal Lake, Srinagar',
      'Cross the dramatic Zoji La pass into the cold desert',
      'Visit Kargil War Memorial — a tribute to India\'s heroes',
      'Moonland landscape at Lamayuru Monastery',
      'Pangong Tso and Nubra Valley circuit from Leh',
      'End in Leh with a summit attempt on Khardung La',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Srinagar', desc: 'Welcome to Srinagar. Dal Lake shikara. Bike briefing.' },
      { day: 'Day 2', title: 'Srinagar – Kargil via Zoji La', desc: 'Cross Zoji La and Sonamarg. Arrive Kargil.' },
      { day: 'Day 3', title: 'Kargil Sightseeing & Ride', desc: 'Visit Kargil War Memorial. Explore Mulbekh Monastery.' },
      { day: 'Day 4', title: 'Kargil – Leh via Lamayuru', desc: 'Moonland at Lamayuru. Arrive Leh.' },
      { day: 'Day 5', title: 'Leh Acclimatization', desc: 'Rest. Explore Leh Palace, Thiksey, Shanti Stupa.' },
      { day: 'Day 6', title: 'Leh – Nubra via Khardung La', desc: 'Summit Khardung La (18,380 ft). Nubra camel safari.' },
      { day: 'Day 7', title: 'Nubra – Pangong via Shyok', desc: 'Shyok River ride to Pangong Tso. Lakeside overnight.' },
      { day: 'Day 8', title: 'Pangong – Leh via Chang La', desc: 'Sunrise at Pangong. Return via Chang La (17,586 ft).' },
      { day: 'Day 9', title: 'Depart Leh', desc: 'Tour concludes. Transfer to airport.' },
    ],
    inclusions: ['Bike with fuel', 'Accommodation (hotel/camp)', 'Breakfast & Dinner daily', 'All permit fees', 'Oxygen cylinder & first aid', 'Expert ride leader & backup vehicle'],
    exclusions: ['Flights / train to Srinagar', 'Lunch', 'Personal expenses', 'Travel insurance'],
    whatsapp: '919541438044',
  },
  {
    id: 10,
    slug: 'leh-ladakh-bike-trip-pocket-friendly-5n6d',
    title: 'LEH LADAKH BIKE TRIP - POCKET FRIENDLY 5N/6D',
    price: '₹15,999',
    priceNote: 'per person',
    image: '/Image/LEHLADAKH.png',
    stats: [
      { icon: '/Image/World.png',    label: 'Altitude', value: '17,582 ft' },
      { icon: '/Image/Location.png', label: 'Distance', value: '350 km' },
      { icon: '/Image/Calender.png', label: 'Duration', value: '5N / 6D' },
      { icon: '/Image/Bed.png',      label: 'Stay',     value: 'Hotel / Camp' },
      { icon: '/Image/Food.png',     label: 'Meals',    value: 'Breakfast & Dinner' },
    ],
    overview: "Ladakh on a budget — without compromising on the experience. This pocket-friendly 6-day Leh-based circuit covers Pangong Lake, Khardung La, and Nubra Valley. Perfect for first-time Ladakh bikers or those with limited time.",
    highlights: [
      'Budget-friendly pricing with all essentials included',
      'Pangong Lake overnight camp — the most iconic experience in Ladakh',
      'Khardung La pass at 18,380 ft',
      'Nubra Valley sand dunes and camel ride',
      'Small group, personalized experience',
      'Royal Enfield Himalayan provided with full support',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Leh', desc: 'Arrival. Acclimatization. Evening city orientation walk.' },
      { day: 'Day 2', title: 'Leh – Nubra via Khardung La', desc: 'Cross Khardung La (18,380 ft). Hunder sand dunes. Camel safari.' },
      { day: 'Day 3', title: 'Nubra – Pangong via Shyok', desc: 'Shyok River to Pangong Tso. Lakeside camp.' },
      { day: 'Day 4', title: 'Pangong – Leh via Chang La', desc: 'Sunrise at Pangong. Return to Leh via Chang La.' },
      { day: 'Day 5', title: 'Leh Local Sightseeing', desc: 'Leh Palace, Thiksey Monastery, Shanti Stupa.' },
      { day: 'Day 6', title: 'Depart Leh', desc: 'Drop to airport or bus station.' },
    ],
    inclusions: ['Bike with fuel', 'Basic hotel/camp accommodation', 'Breakfast & Dinner daily', 'Permit fees', 'First aid kit', 'Ride leader'],
    exclusions: ['Flights / train to Leh', 'Lunch', 'Personal expenses', 'Travel insurance', 'Oxygen cylinder (available on request)'],
    whatsapp: '919541438044',
  },
  {
    id: 11,
    slug: 'manali-leh-manali-group-tour-10n11d',
    title: 'MANALI LEH MANALI GROUP TOUR 10N/11D',
    price: '₹23,999',
    priceNote: 'per person',
    image: 'Image/manali.png',
    stats: [
      { icon: '/Image/World.png',    label: 'Altitude', value: '17,480 ft' },
      { icon: '/Image/Location.png', label: 'Distance', value: '1,000 km' },
      { icon: '/Image/Calender.png', label: 'Duration', value: '10N / 11D' },
      { icon: '/Image/Bed.png',      label: 'Stay',     value: 'Hotel / Camp' },
      { icon: '/Image/Food.png',     label: 'Meals',    value: 'Breakfast & Dinner' },
    ],
    overview: "The classic circular Manali–Leh–Manali group tour — a perfect round-trip adventure through the heart of the Himalayas. Cross Rohtang, Baralacha La, Tanglang La, and Khardung La on this 11-day circuit from New Delhi.",
    highlights: [
      'Round trip from New Delhi — no one-way logistics',
      'Cross all 4 major Manali–Leh passes',
      'Pangong Lake and Nubra Valley included',
      'Group riding — find your tribe on the road',
      'All accommodation, permits, and backup covered',
      'Ideal for first-time Ladakh riders',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Delhi – Manali (Overnight Bus)', desc: 'Depart Delhi by overnight Volvo bus.' },
      { day: 'Day 2', title: 'Arrive Manali & Acclimatize', desc: 'Arrive Manali. Rest and bike handover.' },
      { day: 'Day 3', title: 'Manali – Jispa via Rohtang', desc: 'Cross Rohtang (13,050 ft) and Baralacha La (16,043 ft).' },
      { day: 'Day 4', title: 'Jispa – Sarchu – Leh', desc: 'Cross Tanglang La (17,480 ft). Arrive Leh.' },
      { day: 'Day 5', title: 'Leh Acclimatization', desc: 'Leh sightseeing — palace, monasteries, market.' },
      { day: 'Day 6', title: 'Leh – Nubra via Khardung La', desc: 'Khardung La summit. Nubra Valley & camel safari.' },
      { day: 'Day 7', title: 'Nubra – Pangong via Shyok', desc: 'Shyok River to Pangong. Lakeside overnight.' },
      { day: 'Day 8', title: 'Pangong – Leh via Chang La', desc: 'Chang La crossing and return to Leh.' },
      { day: 'Day 9', title: 'Leh – Sarchu', desc: 'Start return journey. Camp at Sarchu.' },
      { day: 'Day 10', title: 'Sarchu – Manali via Baralacha La', desc: 'Return to Manali.' },
      { day: 'Day 11', title: 'Manali – Delhi (Overnight Bus)', desc: 'Return overnight bus to Delhi.' },
    ],
    inclusions: ['Bike with fuel', 'Accommodation (hotel/camp)', 'Breakfast & Dinner daily', 'Delhi–Manali–Delhi bus', 'Permit fees', 'Expert ride leader & backup vehicle'],
    exclusions: ['Lunch', 'Personal expenses', 'Travel insurance'],
    whatsapp: '919541438044',
  },
  {
    id: 12,
    slug: 'srinagar-to-manali-turtuk-10n11d',
    title: 'SRINAGAR TO MANALI WITH TURTUK 10N & 11D',
    price: '₹35,999',
    priceNote: 'per person',
    image: '/Image/srinagar1.png',
    stats: [
      { icon: '/Image/World.png',    label: 'Altitude', value: '18,380 ft' },
      { icon: '/Image/Location.png', label: 'Distance', value: '1,100 km' },
      { icon: '/Image/Calender.png', label: 'Duration', value: '10N / 11D' },
      { icon: '/Image/Bed.png',      label: 'Stay',     value: 'Hotel / Camp' },
      { icon: '/Image/Food.png',     label: 'Meals',    value: 'Breakfast & Dinner' },
    ],
    overview: "Ride from the paradise of Srinagar to Manali, with a spectacular detour to Turtuk — India's northernmost village on the Line of Control. This 11-day tour blends Kashmir's beauty with Ladakh's extremity and Turtuk's unique Balti culture.",
    highlights: [
      'Start from Srinagar airport — easy access from major cities',
      'Visit Turtuk — the remotest accessible village on the LoC',
      'Khardung La, Chang La, and Zoji La crossings',
      'Pangong Lake and Nubra Valley circuit',
      'End in Manali — the adventure capital of Himachal Pradesh',
      'Comprehensive support team throughout',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Srinagar', desc: 'Welcome to Srinagar. Dal Lake shikara ride. Bike briefing.' },
      { day: 'Day 2', title: 'Srinagar – Kargil via Zoji La', desc: 'Cross Zoji La. Arrive Kargil.' },
      { day: 'Day 3', title: 'Kargil – Leh via Lamayuru', desc: 'Moonland landscape. Arrive Leh.' },
      { day: 'Day 4', title: 'Leh Acclimatization', desc: 'Rest and local sightseeing.' },
      { day: 'Day 5', title: 'Leh – Nubra via Khardung La', desc: 'Summit Khardung La. Nubra Valley.' },
      { day: 'Day 6', title: 'Nubra – Turtuk', desc: 'Ride to Turtuk — India\'s last village before Pakistan. Explore Balti culture and apricot orchards.' },
      { day: 'Day 7', title: 'Turtuk – Pangong via Shyok', desc: 'Scenic Shyok Valley ride to Pangong Tso. Lakeside camp.' },
      { day: 'Day 8', title: 'Pangong – Leh via Chang La', desc: 'Sunrise at the lake. Return to Leh.' },
      { day: 'Day 9', title: 'Leh – Sarchu', desc: 'Begin Manali highway. Camp at Sarchu.' },
      { day: 'Day 10', title: 'Sarchu – Manali via Baralacha La', desc: 'Cross Baralacha La (16,043 ft). Arrive Manali.' },
      { day: 'Day 11', title: 'Depart Manali', desc: 'Tour concludes. Transfer to bus/airport.' },
    ],
    inclusions: ['Bike with fuel', 'Accommodation (hotel/camp)', 'Breakfast & Dinner daily', 'All permit fees', 'Oxygen cylinder & first aid', 'Expert ride leader & backup vehicle'],
    exclusions: ['Flights / train to Srinagar', 'Lunch', 'Personal expenses', 'Travel insurance'],
    whatsapp: '919541438044',
  },
  {
    id: 13,
    slug: 'manali-to-srinagar-turtuk-10n11d',
    title: 'MANALI TO SRINAGAR WITH TURTUK 10N & 11D',
    price: '₹35,999',
    priceNote: 'per person',
    image: '/Image/manali1.png',
    stats: [
      { icon: '/Image/World.png',    label: 'Altitude', value: '18,380 ft' },
      { icon: '/Image/Location.png', label: 'Distance', value: '1,100 km' },
      { icon: '/Image/Calender.png', label: 'Duration', value: '10N / 11D' },
      { icon: '/Image/Bed.png',      label: 'Stay',     value: 'Hotel / Camp' },
      { icon: '/Image/Food.png',     label: 'Meals',    value: 'Breakfast & Dinner' },
    ],
    overview: "The reverse of the Srinagar-to-Manali route — begin in Manali and ride northward, explore all of Ladakh, detour to Turtuk on the Pakistan border, and conclude in Srinagar with a shikara ride on Dal Lake. 11 days of pure adventure departing from Kashmere Gate, Delhi.",
    highlights: [
      'Departs from Kashmere Gate, Delhi — most accessible for North Indian riders',
      'Cross Rohtang, Baralacha La, Tanglang La on the classic Manali–Leh highway',
      'Turtuk — India\'s northernmost accessible village',
      'Pangong Lake, Nubra Valley, and Khardung La',
      'End in Srinagar with Dal Lake shikara ride',
      'Full backup, mechanic, and medical support',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Delhi – Manali (Overnight Bus)', desc: 'Depart Kashmere Gate by overnight bus.' },
      { day: 'Day 2', title: 'Manali – Jispa', desc: 'Arrive Manali, bike handover. Cross Rohtang. Camp at Jispa.' },
      { day: 'Day 3', title: 'Jispa – Sarchu via Baralacha La', desc: 'Cross Baralacha La (16,043 ft). Camp Sarchu.' },
      { day: 'Day 4', title: 'Sarchu – Leh via Tanglang La', desc: 'Cross Tanglang La (17,480 ft). Arrive Leh.' },
      { day: 'Day 5', title: 'Leh Acclimatization', desc: 'Sightseeing and rest.' },
      { day: 'Day 6', title: 'Leh – Nubra via Khardung La', desc: 'Khardung La (18,380 ft). Nubra Valley & camels.' },
      { day: 'Day 7', title: 'Nubra – Turtuk', desc: 'Ride to Turtuk — India\'s last accessible village before LoC.' },
      { day: 'Day 8', title: 'Turtuk – Pangong via Shyok', desc: 'Shyok River to Pangong Tso. Lakeside camp.' },
      { day: 'Day 9', title: 'Pangong – Kargil via Leh', desc: 'Chang La crossing. Drive to Kargil.' },
      { day: 'Day 10', title: 'Kargil – Srinagar via Zoji La', desc: 'Final pass — Zoji La. Arrive Srinagar.' },
      { day: 'Day 11', title: 'Depart Srinagar', desc: 'Dal Lake shikara. Tour concludes.' },
    ],
    inclusions: ['Bike with fuel', 'Accommodation (hotel/camp)', 'Breakfast & Dinner daily', 'Delhi–Manali bus', 'All permit fees', 'Oxygen cylinder & first aid', 'Expert ride leader & backup vehicle'],
    exclusions: ['Return flight from Srinagar', 'Lunch', 'Personal expenses', 'Travel insurance'],
    whatsapp: '919541438044',
  },
  {
    id: 14,
    slug: 'leh-ladakh-bike-tour-6n7d-premium',
    title: 'LEH LADAKH BIKE TOUR - 6N/7D PREMIUM',
    price: '₹41,199',
    priceNote: 'per person',
    image: '/Image/leh1.png',
    stats: [
      { icon: '/Image/World.png',    label: 'Altitude', value: '18,380 ft' },
      { icon: '/Image/Location.png', label: 'Distance', value: '480 km' },
      { icon: '/Image/Calender.png', label: 'Duration', value: '6N / 7D' },
      { icon: '/Image/Bed.png',      label: 'Stay',     value: 'Premium Hotel' },
      { icon: '/Image/Food.png',     label: 'Meals',    value: 'All Meals Included' },
    ],
    overview: "Ladakh's finest — same iconic circuit of Khardung La, Nubra Valley, and Pangong Lake but elevated with premium hotel stays, all meals included, a professional photographer, and a curated experience for those who want the best of both adventure and comfort.",
    highlights: [
      'Premium hotel stays throughout — no camping',
      'All meals included — breakfast, lunch, and dinner',
      'Professional trip photographer to capture every moment',
      'Royal Enfield Himalayan 450 (latest model) provided',
      'Private backup SUV instead of shared support vehicle',
      'VIP permits and priority access at all checkpoints',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive Leh', desc: 'Arrival in premium hotel. Welcome dinner with route briefing.' },
      { day: 'Day 2', title: 'Leh – Nubra via Khardung La', desc: 'Summit Khardung La (18,380 ft). Nubra Valley. Premium desert camp with bonfire.' },
      { day: 'Day 3', title: 'Nubra – Pangong via Shyok', desc: 'Shyok River ride to Pangong. Premium lakeside cottage.' },
      { day: 'Day 4', title: 'Pangong Leisure Day', desc: 'Full day at the lake — sunrise, photography, kayaking, and birdwatching.' },
      { day: 'Day 5', title: 'Pangong – Leh via Chang La', desc: 'Return via Chang La (17,586 ft). Arrival dinner in Leh.' },
      { day: 'Day 6', title: 'Leh Sightseeing & Farewell', desc: 'Monasteries, palaces, local markets. Farewell group dinner.' },
      { day: 'Day 7', title: 'Depart Leh', desc: 'Private transfer to airport. Tour concludes.' },
    ],
    inclusions: ['Royal Enfield Himalayan 450 with fuel', 'Premium hotel/cottage accommodation', 'All meals (breakfast, lunch, dinner)', 'Private backup SUV', 'Professional trip photographer', 'All permit fees', 'Oxygen cylinder & first aid', 'Expert ride leader'],
    exclusions: ['Flights / train to Leh', 'Personal expenses', 'Travel insurance', 'Tips'],
    whatsapp: '919541438044',
  },
]

export default tours